language: cpp
compiler:
  # Comment out for now to keep build matrix small
  #- clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
env:
  global:
    - BAZEL_VERSION="0.6.1"
    - JDK=openjdk8
    # The Travis Ubuntu Trusty environment we run in currently promises 2 cores,
    # so running lengthy make steps with -j2 is almost certainly a win.
    - MAKEFLAGS=-j2
  matrix:
    # Configurations
    #
    # Each line in the ``env`` section represents a set of environment
    # variables passed to a build configuration
    #
    # Test a mix of llvm versions, a mix of build systems, and a mix of shared vs static library
    # Don't build as a static library with cmake. It risks exceeding the travis memory limit.
    - LLVM_VERSION=7.0.0 BUILD_SYSTEM=MAKE CXX_=g++-5 CC_=gcc-5
    # - LLVM_VERSION=6.0.0 BUILD_SYSTEM=MAKE CXX_=g++-5 CC_=gcc-5
    - LLVM_VERSION=7.0.0 BUILD_SYSTEM=CMAKE CXX_=g++-5 CC_=gcc-5 HALIDE_SHARED_LIBRARY=1
cache: apt ccache
dist: trusty
sudo: require
# Note the commands below are written assuming Ubuntu 14.04LTS
before_install:
  # Needed for new libstdc++ and gcc5
  - export CXX=${CXX_}
  - export CC=${CC_}
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test/
  - sudo apt-get update
  - wget https://github.com/bazelbuild/bazel/releases/download/"${BAZEL_VERSION}"/bazel_"${BAZEL_VERSION}"-linux-x86_64.deb
  - sudo dpkg -i bazel_"${BAZEL_VERSION}"-linux-x86_64.deb
install:
  - sudo apt-get -y --force-yes install ${CXX} ${CC} libedit-dev
  # Make gcc4.8 the default gcc version
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/${CC} 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/${CXX} 20
  # Download the right llvm release
  - wget https://releases.llvm.org/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - tar xvf clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - sudo mv clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04 /usr/local/llvm
  # Get libpng for the tutorials and apps
  - sudo apt-get -y --force-yes install libpng-dev
  # For generating docs
  - sudo apt-get -y --force-yes --no-install-recommends install doxygen
script:
  - test/scripts/build_travis.sh
